version: 2.1

orbs:
  node: circleci/node@5.0.2  # Orbe oficial para Node.js

executors:
  node14:
    docker:
      - image: cimg/node:14.18.2  # Imagen de Node.js
    resource_class: medium

commands:
  nodesetup:
    description: "Setup del proyecto con checkout y dependencias"
    steps:
      - checkout  # Clona el repositorio
      - run:
          name: Verificar Archivos y Directorios
          command: |
            echo "Verificando estructura de archivos:"
            pwd  # Muestra el directorio actual
            ls -Rla  # Lista todos los archivos de forma recursiva

jobs:
  build_and_test:
    executor: node14
    steps:
      - nodesetup  # Configura y verifica los archivos
      - run:
          name: Instalar Dependencias y Ejecutar Pruebas
          command: |
            if [ -d "circleci-nodejs-master" ]; then
              cd circleci-nodejs-master
              npm install
              npm run coverage
            else
              echo "Error: La carpeta circleci-nodejs-master no existe"
              exit 1
            fi
      - store_artifacts:
          path: circleci-nodejs-master/coverage
          prefix: coverage

workflows:
  version: 2

  node_build_pipeline:
    jobs:
      - build_and_test
