version: 2.1

executors:
  node_executor:
    docker:
      - image: node:18  # Usa la imagen oficial de Node.js 18

jobs:
  install_dependencies:
    executor: node_executor
    steps:
      - checkout
      - run: npm install

  lint:
    executor: node_executor
    steps:
      - checkout
      - run: npm install
      - run: npm run lint

  test_unit:
    executor: node_executor
    parallelism: 2
    steps:
      - checkout
      - run: npm install
      - run: npm run test:unit

  test_integration:
    executor: node_executor
    steps:
      - checkout
      - run: npm install
      - run: npm run test:integration

  notify:
    executor: node_executor
    steps:
      - run: |
          echo "Notificación: El pipeline se ha completado con éxito"
          curl -X POST -H "Content-Type: application/json" \
          -d '{"text": "Pipeline completado: '"${CIRCLE_WORKFLOW_ID}"'"}' \
          https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK

workflows:
  version: 2

  complete_pipeline:
    jobs:
      - install_dependencies
      - lint:
          requires:
            - install_dependencies
      - test_unit:
          requires:
            - lint
      - test_integration:
          requires:
            - test_unit
      - notify:
          requires:
            - test_integration  # Envía notificación tras las pruebas de integración