version: 2.1

orbs:
  node: circleci/node@5.0.2

executors:
  node14:
    docker:
      - image: cimg/node:14.18.2  # Imagen oficial de Node.js 14.18.2
    resource_class: medium

commands:
  nodesetup:
    description: "Checkout, restore cache, install dependencies"
    steps:
      - checkout  # Clona el repositorio
      - run:
          name: Cambiar al directorio correcto
          command: cd circleci-nodejs-master/circleci-nodejs-master  # Cambia al subdirectorio donde están los archivos
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}  # Usa la caché si está disponible
      - node/install-packages:
          cache-path: ~/project/node_modules
          app-dir: ~/project/circleci-nodejs-master/circleci-nodejs-master  # Ruta correcta del proyecto
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

jobs:
  build_and_test:
    executor: node14
    steps:
      - nodesetup  # Ejecuta el setup para instalar dependencias
      - run:
          name: Ejecutar Coverage
          command: |
            cd circleci-nodejs-master/circleci-nodejs-master
            npm run coverage  # Ejecuta las pruebas de cobertura
      - restore_cache:
          keys:
            - v1-result-cache
      - run:
          name: Coverage Test
          command: |
            mv /tmp/result /tmp/result-moved || true
            npx lcov-total coverage/lcov.info > /tmp/result
            chmod u+x coveragetest.sh
            ./coveragetest.sh
      - save_cache:
          paths:
            - coverage
          key: v1-result-cache
      - store_artifacts:  # Guarda los reportes como artefactos
          path: circleci-nodejs-master/circleci-nodejs-master/coverage
          prefix: coverage

workflows:
  version: 2

  node_build_pipeline:
    jobs:
      - build_and_test  # Ejecuta el job de construcción y pruebas
