version: 2.1

orbs:
  node: circleci/node@5.0.2

executors:
  node14:
    docker:
      - image: cimg/node:14.18.2  # Imagen oficial de Node.js 14.18.2
    resource_class: medium

commands:
  nodesetup:
    description: "Checkout, restore cache, install dependencies"
    steps:
      - checkout  # Clona el repositorio
      - run:
          name: Cambiar al directorio correcto
          command: cd circleci-nodejs-master/circleci-nodejs-master  # Cambia al subdirectorio donde están los archivos
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}  # Usa la caché si está disponible
      - node/install-packages:
          cache-path: ~/project/node_modules
          app-dir: ~/project/circleci-nodejs-master/circleci-nodejs-master  # Ruta correcta del proyecto
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

jobs:
  jobs:
  build_and_test:
    executor: node14
    steps:
      - checkout  # Clona el repositorio
      - run:
          name: Listar Directorio Actual
          command: |
            echo "Listando archivos en el directorio actual"
            pwd  # Muestra la ruta actual
            ls -la  # Lista todos los archivos y carpetas
      - run:
          name: Listar Contenido de Subdirectorios
          command: |
            echo "Verificando contenido de circleci-nodejs-master"
            ls -la circleci-nodejs-master  # Verifica que exista la carpeta


workflows:
  version: 2

  node_build_pipeline:
    jobs:
      - build_and_test  # Ejecuta el job de construcción y pruebas
