version: 2.1

orbs:
  node: circleci/node@5.0.2  # Orbe oficial para Node.js

executors:
  node14:
    docker:
      - image: cimg/node:14.18.2  # Imagen de Node.js
    resource_class: medium

commands:
  nodesetup:
    description: "Checkout, restore cache, install dependencies"
    steps:
      - checkout  # Clona el repositorio
      - run:
          name: Listar Archivos en Directorio Actual
          command: |
            echo "Listando archivos:"
            pwd  # Muestra el directorio actual
            ls -la  # Lista archivos para verificar la estructura
      - run:
          name: Mover al Directorio Correcto
          command: cd circleci-nodejs-master  # Cambia a la carpeta correcta
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "circleci-nodejs-master/package-lock.json" }}  # Cachea dependencias
      - node/install-packages:
          cache-path: ~/project/circleci-nodejs-master/node_modules
          app-dir: ~/project/circleci-nodejs-master  # Ruta correcta del proyecto
      - save_cache:
          paths:
            - circleci-nodejs-master/node_modules
          key: v1-dependencies-{{ checksum "circleci-nodejs-master/package-lock.json" }}

jobs:
  build_and_test:
    executor: node14
    steps:
      - nodesetup  # Ejecuta los pasos de setup y dependencias
      - run:
          name: Ejecutar Pruebas de Cobertura
          command: |
            cd circleci-nodejs-master
            npm run coverage  # Ejecuta la cobertura
      - store_artifacts:
          path: circleci-nodejs-master/coverage  # Guarda los reportes
          prefix: coverage

workflows:
  version: 2

  node_build_pipeline:
    jobs:
      - build_and_test  # Ejecuta el job de construcción y pruebas
