version: 2.1

orbs:
  node: circleci/node@5.0.2

executors:
  node14:
    docker:
      - image: cimg/node:14.18.2
    resource_class: medium

commands:
  nodesetup:
    description: "Checkout, restore cache, install dependencies"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - node/install-packages:
          cache-path: ~/project/node_modules
          app-dir: ~/project  # Asegura que apunta al directorio correcto
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

jobs:
  build_and_test:
    executor: node14
    steps:
      - nodesetup
      - run:
          name: Ejecutar Coverage
          command: npm run coverage
      - restore_cache:
          keys:
            - v1-result-cache
      - run:
          name: Coverage Test
          command: |
            mv /tmp/result /tmp/result-moved || true
            npx lcov-total coverage/lcov.info > /tmp/result
            chmod u+x coveragetest.sh
            ./coveragetest.sh
      - save_cache:
          paths:
            - coverage
          key: v1-result-cache
      - store_artifacts:
          path: coverage
          prefix: coverage

workflows:
  version: 2

  node_build_pipeline:
    jobs:
      - build_and_test


