version: 2.1

orbs:
  node: circleci/node@5.0.2  # Orbe oficial para Node.js

executors:
  node14:
    docker:
      - image: cimg/node:14.18.2  # Imagen de Node.js
    resource_class: medium

commands:
  nodesetup:
    description: "Setup del proyecto con checkout, caché y dependencias"
    steps:
      - checkout  # Clona el repositorio
      - run:
          name: Verificar Estructura del Proyecto
          command: |
            echo "Listando archivos en el directorio actual:"
            pwd  # Muestra la ruta actual
            ls -la  # Lista archivos para verificar
      - run:
          name: Instalar Dependencias y Ejecutar Cobertura
          command: |
            cd circleci-nodejs-master
            echo "Instalando dependencias..."
            npm install  # Instala las dependencias
            echo "Ejecutando pruebas de cobertura..."
            npm run coverage  # Ejecuta la cobertura
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "circleci-nodejs-master/package-lock.json" }}
      - save_cache:
          paths:
            - circleci-nodejs-master/node_modules
          key: v1-dependencies-{{ checksum "circleci-nodejs-master/package-lock.json" }}
      - store_artifacts:
          path: circleci-nodejs-master/coverage  # Guarda los reportes como artefactos
          prefix: coverage

jobs:
  build_and_test:
    executor: node14
    steps:
      - nodesetup  # Configura el entorno y ejecuta las pruebas

workflows:
  version: 2

  node_build_pipeline:
    jobs:
      - build_and_test  # Ejecuta la construcción y pruebas
